
var:
  bluish_version: "0.0.1"
  python_version: "3.11"

jobs:
  lint:
    name: Runs ruff and mypy
    steps:
      - run: |
          ruff version
          ruff check src/ test/
          echo ""
          mypy --version
          mypy --ignore-missing-imports --python-version=${{ pipe.python_version }} src/ test/

  lint-fix:
    name: Reformats the code using ruff
    steps:
      - run: |
          ruff version
          ruff check --select I --fix src/ test/
          ruff format src/
          echo ""

  test:
    name: Runs pytest
    steps:
      - run: |
          pytest
  
  update-metadata:
    name: Updates the info present in the pyproject.toml file
    steps:
      - uses: expand-template
        with:
          input_file: ./pyproject.toml.template
          output_file: ./pyproject.toml
