
var:
  PROJECT_VERSION: "0.0.1"

jobs:
  update-metadata:
    name: Updates the info present in the pyproject.toml file
    steps:
      - uses: core/expand-template
        is_sensitive: true
        with:
          input_file: ./templates/pyproject.toml.template
          output_file: ./pyproject.toml
