
var:
  project_version: "0.0.29"

jobs:
  publish:

    name: Publishes the latest release of Bluish 

    runs_on: docker://python:3.12-alpine

    steps:
      - uses: linux/install-packages
        with:
          packages:
            - jq
            - curl

      - run: |
          pypi_version=$(curl -s https://pypi.org/pypi/bluish/json | jq -r .info.version)
          echo "pypi_version=$pypi_version" >> "$BLUISH_OUTPUT"
        set:
          workflow.var.pypi_version: ${{ outputs.pypi_version }}

      - name: Check if we got a valid PYPI_VERSION
        run: |
          [ "${{ pypi_version }}" != "" ]

      - uses: git/checkout
        with:
          repository: https://github.com/luismedel/bluish

      - name: Check if upload is needed
        run: |
          [ "${{ project_version }}" != "${{ pypi_version }}" ]

      - name: Update metadata in pyproject.toml
        uses: core/expand-template
        with:
          input_file: ./templates/pyproject.toml.template
          output_file: ./pyproject.toml

      - name: Update metadata in src/bluish/__main__.py
        uses: core/expand-template
        with:
          input_file: ./templates/__main__.py.template
          output_file: ./src/bluish/__main__.py

      - name: Build project
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Prepare credentials
        uses: core/upload-file
        is_sensitive: true
        with:
          source_file: ~/.pypirc
          destination_file: ~/.pypirc

      - name: Deploy to Pypi
        run: |
          python -m pip install --upgrade twine
          python -m twine upload dist/*
