
var:
  python_version: "3.11"

jobs:
  _prepare_lint:
    name: Prepare linters
    steps:
      - run: |
          pip3 install -r requirements-linting.txt

  lint:
    name: Runs ruff and mypy
    depends_on: [_prepare_lint]
    steps:
      - run: |
          ruff version
          ruff check src/ test/
          echo ""
          mypy --version
          mypy --ignore-missing-imports --python-version=${{ python_version }} src/ test/

  fix:
    name: Reformats the code using ruff
    depends_on: [lint]
    steps:
      - run: |
          ruff version
          ruff check --select I --fix src/ test/
          ruff format src/
          echo ""

  _prepare_tests:
    name: Prepare tests
    steps:
      - run: |
          pip3 install -r requirements-testing.txt

  test:
    name: Runs pytest
    depends_on: [_prepare_tests]
    steps:
      - run: |
          pytest -n 2

  test-all:
    name: Runs pytest
    depends_on: [_prepare_tests]
    steps:
      - run: |
          pytest -n 2 --run-docker
