
var:
  python_version: "3.12"

inputs:
  - name: test
    default: 1

jobs:
  _prepare_lint:
    name: Prepare linters
    steps:
      - run: |
          pip3 install -r requirements-linting.txt

  lint:
    name: Run ruff and mypy
    depends_on: [_prepare_lint]
    steps:
      - run: |
          ruff version
          ruff check src/ test/
          echo ""
          mypy --version
          mypy --ignore-missing-imports --python-version=${{ python_version }} src/ test/

  fix:
    name: Reformat the code using ruff
    steps:
      - run: |
          ruff version
          ruff check --select I --fix src/ test/
          ruff format src/
          echo ""

  _prepare_tests:
    name: Prepare tests
    steps:
      - run: |
          pip3 install -r requirements-testing.txt

  test:
    name: Run basic test suite
    depends_on: [_prepare_tests]
    steps:
      - run: |
          pytest -n 2

  test-all:
    name: Run full test suite
    depends_on: [_prepare_tests]
    steps:
      - run: |
          pytest -n 2 --run-docker
