
var:
  PYTHON_VERSION: "3.11"

jobs:
  lint:
    name: Runs ruff and mypy
    steps:
      - run: |
          ruff version
          ruff check src/ test/
          echo ""
          mypy --version
          mypy --ignore-missing-imports --python-version=${{ PYTHON_VERSION }} src/ test/

  lint-fix:
    name: Reformats the code using ruff
    depends_on:
      - lint
    steps:
      - run: |
          ruff version
          ruff check --select I --fix src/ test/
          ruff format src/
          echo ""

  test:
    name: Runs pytest
    steps:
      - run: |
          pytest -n 2
