
var:
  PYTHON_VERSION: "3.12"

jobs:
  ci:
    runs_on: docker://python:${{ PYTHON_VERSION }}-alpine
    steps:
      - uses: git/checkout
        with:
          repository: https://github.com/luismedel/bluish

      - name: Prepare the environment
        run: |
          pip3 install -r requirements-linting.txt
          pip3 install -r requirements-testing.txt

      - name: Run ruff and mypy
        run: |
          ruff version
          ruff check src/ test/
          echo ""
          mypy --version
          mypy --ignore-missing-imports --python-version=${{ PYTHON_VERSION }} src/ test/

      - name: Runs pytest
        run: |
          pytest -k "not docker" -n 2
