name: Fire the publish workflow using Bluish

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          python3 -m venv .e
          . .e/bin/activate
          pip install bluish
          blu publish
