name: Fire the publish workflow using Bluish

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: luismedel/setup-bluish@v3
      - run: |
          pip3 install -r requirements-testing.txt
      - run: |
          blu ci:test-all
