name: Fire the publish workflow using Bluish

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python3 -m venv .e
          . .e/bin/activate
          pip install --upgrade pip
          pip install bluish
          blu ci:test-all
