name: CI 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: luismedel/setup-bluish@v3
      - run: |
          blu ci:lint
          blu ci:test-all
